kind: ReplicationController
apiVersion: v1
metadata: 
  name: demo-controller
  labels: 
    name: demo
spec: 
 replicas: 3
 selector: 
   app: demo
 template: 
   metadata:
     labels: 
       app: demo 
   spec: 
     containers:
     - image: liontechacademy/april23repo:nexus-v1
       name: demo-controller
       ports: 
       - containerPort: 8081
         name: demo 

---
kind: Service
apiVersion: v1
metadata: 
  labels: 
    app: demo
  name: demo
spec: 
  selector: 
    app: demo
  type: NodePort
  ports: 
  - port: 8081 
    protocol: TCP
    targetPort: 8081
    nodePort: 31222
